version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: restaurant_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mokhtar1.
      POSTGRES_DB: restaurantdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: restaurant_backend
    environment:
      FLASK_ENV: docker
      DOCKER_ENV: 1
      DATABASE_URL: postgresql://postgres:Mokhtar1.@postgres:5432/restaurantdb
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: restaurant_frontend
    command: ["npm", "start"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
